import sqlite3
import pandas as pd
from config import CACHE_DB_PATH

def get_connection():
    return sqlite3.connect(CACHE_DB_PATH)

def init_db():
    """Create tables if they don't exist."""
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS ohlcv_cache (
            ticker      TEXT,
            date        TEXT,
            open        REAL,
            high        REAL,
            low         REAL,
            close       REAL,
            volume      REAL,
            PRIMARY KEY (ticker, date)
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS signal_log (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            ticker      TEXT,
            signal      TEXT,
            entry_low   REAL,
            entry_high  REAL,
            stop_loss   REAL,
            target1     REAL,
            target2     REAL,
            rr_ratio    REAL,
            reasoning   TEXT,
            created_at  TEXT DEFAULT (datetime('now','localtime'))
        )
    """)

    conn.commit()
    conn.close()
    print("[db] Tables ready.")

def save_ohlcv(ticker: str, df: pd.DataFrame):
    """Save OHLCV dataframe to cache."""
    conn = get_connection()
    for date, row in df.iterrows():
        try:
            conn.execute("""
                INSERT OR REPLACE INTO ohlcv_cache
                (ticker, date, open, high, low, close, volume)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                ticker,
                str(date.date()),
                float(row.get("Open",  0)),
                float(row.get("High",  0)),
                float(row.get("Low",   0)),
                float(row.get("Close", 0)),
                float(row.get("Volume",0)),
            ))
        except Exception as e:
            print(f"[db] save error for {ticker} {date}: {e}")
    conn.commit()
    conn.close()

def load_ohlcv(ticker: str) -> pd.DataFrame:
    """Load cached OHLCV for a ticker."""
    conn = get_connection()
    df = pd.read_sql_query(
        "SELECT * FROM ohlcv_cache WHERE ticker=? ORDER BY date ASC",
        conn, params=(ticker,)
    )
    conn.close()
    if not df.empty:
        df["date"] = pd.to_datetime(df["date"])
        df.set_index("date", inplace=True)
    return df

def log_signal(ticker: str, signal: dict):
    """Save a buy/sell signal generated by the agent."""
    conn = get_connection()
    conn.execute("""
        INSERT INTO signal_log
        (ticker, signal, entry_low, entry_high, stop_loss, target1, target2, rr_ratio, reasoning)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        ticker,
        signal.get("signal"),
        signal.get("entry_low"),
        signal.get("entry_high"),
        signal.get("stop_loss"),
        signal.get("target1"),
        signal.get("target2"),
        signal.get("rr_ratio"),
        signal.get("reasoning"),
    ))
    conn.commit()
    conn.close()

def get_signal_history(ticker: str = None) -> pd.DataFrame:
    """Retrieve past signals. Pass ticker to filter, or None for all."""
    conn = get_connection()
    if ticker:
        df = pd.read_sql_query(
            "SELECT * FROM signal_log WHERE ticker=? ORDER BY created_at DESC",
            conn, params=(ticker,)
        )
    else:
        df = pd.read_sql_query(
            "SELECT * FROM signal_log ORDER BY created_at DESC",
            conn
        )
    conn.close()
    return df


# ── quick test ──────────────────────────────────────────────
if __name__ == "__main__":
    init_db()

    # test saving OHLCV
    from data.fetcher import get_historical_ohlcv
    df = get_historical_ohlcv("RELIANCE.NS", period="5d")
    save_ohlcv("RELIANCE.NS", df)
    print("[db] Saved RELIANCE OHLCV to cache.")

    # test loading it back
    cached = load_ohlcv("RELIANCE.NS")
    print(f"[db] Loaded {len(cached)} rows from cache:")
    print(cached.tail(3))