import streamlit as st
import pandas as pd
from storage.db import init_db, get_signal_history

st.set_page_config(page_title="History", page_icon="📋", layout="wide")
st.title("📋 Signal History")
st.caption("All past signals generated by the agent")

init_db()

col1, col2 = st.columns([2,1])
with col1:
    ticker_filter = st.text_input("Filter by ticker (leave blank for all)", "")
with col2:
    st.write("")
    st.write("")
    refresh = st.button("🔄 Refresh")

df = get_signal_history(ticker_filter.upper() if ticker_filter else None)

if df.empty:
    st.info("No signals yet. Run the Analyzer to generate signals.")
else:
    total  = len(df)
    buys   = len(df[df["signal"] == "BUY"])
    avoids = len(df[df["signal"] == "AVOID"])

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Signals", total)
    col2.metric("BUY signals",   buys)
    col3.metric("AVOID signals", avoids)

    st.divider()
    st.dataframe(df, use_container_width=True, hide_index=True)